import { addDays, format, setHours, setMinutes, setSeconds, startOfDay } from "date-fns";
import { tr } from "date-fns/locale";
import type { ContentType, SocialPlatform } from "@/generated/prisma/enums";
import {
  type ContentPlanTargets,
  targetsToTypeCounts,
} from "@/lib/content-plan";
import { contentTypeLabels } from "@/lib/labels";
import { prisma } from "@/lib/db";
import {
  parseStoredPlanTimes,
  publishAtOnDay,
  timeForSlot,
  type PlanTimes,
} from "@/lib/plan-times";
import {
  occurrenceDateKey,
  parseSkippedOccurrenceDates,
  shouldSpawnOnDay,
} from "@/lib/recurring-tasks";

function noonOn(day: Date) {
  return setSeconds(setMinutes(setHours(startOfDay(day), 12), 0), 0);
}

/** Bir gün için eksik post/story/reel/video içeriklerini oluşturur / saatleri senkronlar. */
export async function ensureContentSlotsForDay(opts: {
  companyId: string;
  companyName: string;
  authorId: string;
  day: Date;
  targets: ContentPlanTargets;
  platform?: SocialPlatform;
  schedule?: PlanTimes;
}) {
  const typeCounts = targetsToTypeCounts(opts.targets);
  if (typeCounts.length === 0) return 0;

  const dayStart = startOfDay(opts.day);
  const dayEnd = addDays(dayStart, 1);
  const platform = opts.platform ?? "INSTAGRAM";
  const dayLabel = format(dayStart, "d MMM", { locale: tr });

  let created = 0;

  for (const { type, count } of typeCounts) {
    const existing = await prisma.content.findMany({
      where: {
        companyId: opts.companyId,
        type: type as ContentType,
        publishAt: { gte: dayStart, lt: dayEnd },
      },
      orderBy: [{ createdAt: "asc" }, { id: "asc" }],
      select: {
        id: true,
        publishAt: true,
        autoGenerated: true,
      },
    });

    const need = Math.max(0, count - existing.length);
    for (let n = 1; n <= need; n += 1) {
      const index = existing.length + n; // 1-based label
      const slotIndex = existing.length + n - 1; // 0-based schedule
      const hhmm = timeForSlot(opts.schedule, type as ContentType, slotIndex);
      await prisma.content.create({
        data: {
          title: `${opts.companyName} · ${contentTypeLabels[type as ContentType]} ${index} · ${dayLabel}`,
          body: "(Taslak — görev hedefinden)",
          platform,
          type: type as ContentType,
          publishAt: publishAtOnDay(dayStart, hhmm),
          notes: "Görev hedeflerinden otomatik dağıtıldı",
          autoGenerated: true,
          companyId: opts.companyId,
          authorId: opts.authorId,
          status: "SCHEDULED",
        },
      });
      created += 1;
    }

    // Mevcut otomatik içeriklerin saatlerini plana hizala
    const all = await prisma.content.findMany({
      where: {
        companyId: opts.companyId,
        type: type as ContentType,
        publishAt: { gte: dayStart, lt: dayEnd },
      },
      orderBy: [{ createdAt: "asc" }, { id: "asc" }],
      select: { id: true, publishAt: true, autoGenerated: true },
      take: count,
    });

    for (let i = 0; i < all.length; i += 1) {
      const row = all[i]!;
      if (!row.autoGenerated) continue;
      const hhmm = timeForSlot(opts.schedule, type as ContentType, i);
      const next = publishAtOnDay(dayStart, hhmm);
      if (
        !row.publishAt ||
        row.publishAt.getTime() !== next.getTime()
      ) {
        await prisma.content.update({
          where: { id: row.id },
          data: { publishAt: next },
        });
      }
    }
  }

  return created;
}

async function resolvePlatform(companyId: string): Promise<SocialPlatform> {
  const account = await prisma.socialAccount.findFirst({
    where: { companyId, status: "ACTIVE" },
    select: { platform: true },
    orderBy: { platform: "asc" },
  });
  return (account?.platform as SocialPlatform) ?? "INSTAGRAM";
}

/**
 * Açık görevlerdeki post/story hedeflerini takvimde tiklenebilir
 * içerik satırlarına çevirir (eksik olanları tamamlar).
 */
export async function ensureContentSlotsFromTasks(opts?: {
  daysAhead?: number;
  from?: Date;
}) {
  const daysAhead = Math.min(Math.max(opts?.daysAhead ?? 7, 1), 31);
  const from = startOfDay(opts?.from ?? new Date());

  const tasks = await prisma.task.findMany({
    where: {
      status: { not: "DONE" },
      companyId: { not: null },
      OR: [
        { planPosts: { gt: 0 } },
        { planStories: { gt: 0 } },
        { planReels: { gt: 0 } },
        { planVideos: { gt: 0 } },
      ],
      // Şablon veya tek seferlik; kopyalardaki hedefler 0 olacak
      recurrenceOfId: null,
    },
    include: {
      company: { select: { id: true, name: true } },
    },
  });

  let created = 0;

  for (const task of tasks) {
    if (!task.companyId || !task.company) continue;

    const targets: ContentPlanTargets = {
      planPeriod: task.planPeriod,
      planPosts: task.planPosts,
      planStories: task.planStories,
      planReels: task.planReels,
      planVideos: task.planVideos,
    };
    const schedule = parseStoredPlanTimes(task.planTimes);
    const platform = await resolvePlatform(task.companyId);
    const authorId = task.assigneeId ?? task.creatorId;

    const skipped = new Set(
      parseSkippedOccurrenceDates(task.skippedOccurrenceDates),
    );
    const days: Date[] = [];
    // Takvime yayma SADECE otomatik yinelemeden gelir; plan dönemi sadece hedef sayımıdır
    if (task.recurrence === "DAILY") {
      for (let i = 0; i < daysAhead; i += 1) days.push(addDays(from, i));
    } else if (task.recurrence === "WEEKLY" || task.recurrence === "MONTHLY") {
      const anchor = task.dueDate ?? task.startDate ?? task.createdAt;
      for (let i = 0; i < daysAhead; i += 1) {
        const day = addDays(from, i);
        if (shouldSpawnOnDay(task.recurrence, anchor, day)) days.push(day);
      }
    } else if (task.dueDate) {
      days.push(startOfDay(task.dueDate));
    } else {
      days.push(from);
    }

    for (const day of days) {
      if (skipped.has(occurrenceDateKey(day))) continue;
      created += await ensureContentSlotsForDay({
        companyId: task.companyId,
        companyName: task.company.name,
        authorId,
        day,
        targets,
        platform,
        schedule,
      });
    }
  }

  return { created };
}

/**
 * Dün ve öncesinde tamamlanan paylaşımlar + görev kopyalarını siler.
 * Bugün sayfası / takvim açılınca çalışır.
 */
export async function pruneCompletedPastWork(opts?: { before?: Date }) {
  const before = startOfDay(opts?.before ?? new Date());

  const [contents, tasks] = await Promise.all([
    prisma.content.deleteMany({
      where: {
        status: "PUBLISHED",
        OR: [
          { publishAt: { lt: before } },
          { publishAt: null, createdAt: { lt: before } },
        ],
      },
    }),
    prisma.task.deleteMany({
      where: {
        status: "DONE",
        // Şablonları silme; günlük kopyalar ve tek seferlikler
        NOT: {
          AND: [{ recurrenceOfId: null }, { recurrence: { not: "NONE" } }],
        },
        OR: [
          { occurrenceDate: { lt: before } },
          {
            occurrenceDate: null,
            dueDate: { lt: before },
          },
        ],
      },
    }),
  ]);

  return { contentsDeleted: contents.count, tasksDeleted: tasks.count };
}

/**
 * Açık iş/şablon kapsamayan günlerdeki paylaşımları siler
 * (Bugün / takvimde silinen işlerin içeriği kalmasın).
 */
export async function pruneOrphanAutoContents(opts?: {
  daysAhead?: number;
  from?: Date;
}) {
  const daysAhead = Math.min(Math.max(opts?.daysAhead ?? 14, 1), 31);
  const from = startOfDay(opts?.from ?? new Date());
  const rangeEnd = addDays(from, daysAhead);

  const [contents, coverTasks] = await Promise.all([
    prisma.content.findMany({
      where: {
        OR: [
          { publishAt: { gte: from, lt: rangeEnd } },
          {
            publishAt: null,
            createdAt: { gte: from, lt: rangeEnd },
          },
        ],
      },
      select: { id: true, companyId: true, publishAt: true, createdAt: true },
    }),
    prisma.task.findMany({
      where: {
        status: { not: "DONE" },
        companyId: { not: null },
        OR: [
          {
            recurrenceOfId: null,
            OR: [
              { planPosts: { gt: 0 } },
              { planStories: { gt: 0 } },
              { planReels: { gt: 0 } },
              { planVideos: { gt: 0 } },
              { recurrence: { in: ["DAILY", "WEEKLY", "MONTHLY"] } },
            ],
          },
          { recurrenceOfId: { not: null } },
        ],
      },
      select: {
        companyId: true,
        recurrence: true,
        recurrenceOfId: true,
        occurrenceDate: true,
        dueDate: true,
        startDate: true,
        createdAt: true,
        planPosts: true,
        planStories: true,
        planReels: true,
        planVideos: true,
        planPeriod: true,
        skippedOccurrenceDates: true,
      },
    }),
  ]);

  if (contents.length === 0) return { deleted: 0 };

  const covered = new Set<string>();

  for (const task of coverTasks) {
    if (!task.companyId) continue;

    if (task.recurrenceOfId && task.occurrenceDate) {
      covered.add(
        `${task.companyId}:${occurrenceDateKey(task.occurrenceDate)}`,
      );
      continue;
    }

    const hasPlan =
      task.planPosts + task.planStories + task.planReels + task.planVideos > 0;
    if (!hasPlan && task.recurrence === "NONE") continue;

    const skipped = new Set(
      parseSkippedOccurrenceDates(task.skippedOccurrenceDates),
    );
    const anchor = task.dueDate ?? task.startDate ?? task.createdAt;

    if (
      task.recurrence === "DAILY" ||
      task.recurrence === "WEEKLY" ||
      task.recurrence === "MONTHLY"
    ) {
      for (let i = 0; i < daysAhead; i += 1) {
        const day = addDays(from, i);
        if (!shouldSpawnOnDay(task.recurrence, anchor, day)) continue;
        const key = occurrenceDateKey(day);
        if (skipped.has(key)) continue;
        covered.add(`${task.companyId}:${key}`);
      }
    } else if (task.dueDate) {
      const key = occurrenceDateKey(task.dueDate);
      if (!skipped.has(key)) covered.add(`${task.companyId}:${key}`);
    } else {
      const key = occurrenceDateKey(from);
      if (!skipped.has(key)) covered.add(`${task.companyId}:${key}`);
    }
  }

  const orphanIds = contents
    .filter((c) => {
      const day = c.publishAt ?? c.createdAt;
      const key = `${c.companyId}:${occurrenceDateKey(day)}`;
      return !covered.has(key);
    })
    .map((c) => c.id);

  if (orphanIds.length === 0) return { deleted: 0 };

  await prisma.content.deleteMany({ where: { id: { in: orphanIds } } });
  return { deleted: orphanIds.length };
}

/** @deprecated kept for callers that imported noon helper indirectly */
export { noonOn };
