import Link from "next/link";
import { Button, Card, Chip } from "@heroui/react";
import { addDays, format, startOfDay } from "date-fns";
import { tr } from "date-fns/locale";
import { syncRecurringTasks } from "@/actions/tasks";
import { ContentPlanSummary } from "@/components/contents/content-plan-summary";
import {
  WorkBulkItem,
  WorkBulkList,
} from "@/components/work/work-bulk-list";
import {
  FormField,
  SelectInput,
} from "@/components/ui/form-field";
import { TaskStatus } from "@/generated/prisma/client";
import { prisma } from "@/lib/db";
import {
  contentStatusLabels,
  contentTypeLabels,
  planPeriodLabels,
  taskPriorityLabels,
  taskRecurrenceLabels,
  taskStatusLabels,
} from "@/lib/labels";
import { excludeTaskTemplatesFilter } from "@/lib/recurring-tasks";
import { requireAdmin } from "@/lib/session";
import type { ContentPlanItem } from "@/lib/content-plan-types";

function dayKey(companyId: string, day: Date) {
  return `${companyId}:${startOfDay(day).toISOString()}`;
}

function planItemsFromTask(task: {
  planPosts: number;
  planStories: number;
  planReels: number;
  planVideos: number;
}): ContentPlanItem[] {
  return [
    {
      type: "POST",
      label: contentTypeLabels.POST,
      done: 0,
      target: task.planPosts,
    },
    {
      type: "STORY",
      label: contentTypeLabels.STORY,
      done: 0,
      target: task.planStories,
    },
    {
      type: "REEL",
      label: contentTypeLabels.REEL,
      done: 0,
      target: task.planReels,
    },
    {
      type: "VIDEO",
      label: contentTypeLabels.VIDEO,
      done: 0,
      target: task.planVideos,
    },
  ];
}

export default async function WorkPage({
  searchParams,
}: {
  searchParams: Promise<{ company?: string; status?: string }>;
}) {
  await requireAdmin();
  const admin = true;
  const sp = await searchParams;

  await syncRecurringTasks(31);

  const status =
    sp.status && Object.keys(TaskStatus).includes(sp.status)
      ? (sp.status as TaskStatus)
      : undefined;

  const [tasks, templates, companies] = await Promise.all([
    prisma.task.findMany({
      where: {
        ...excludeTaskTemplatesFilter(),
        ...(sp.company ? { companyId: sp.company } : {}),
        ...(status ? { status } : {}),
      },
      include: { company: true, assignee: true, creator: true },
      orderBy: [{ dueDate: "asc" }, { updatedAt: "desc" }],
    }),
    prisma.task.findMany({
      where: {
        recurrence: { not: "NONE" },
        recurrenceOfId: null,
        ...(sp.company ? { companyId: sp.company } : {}),
      },
      include: { company: true, assignee: true },
      orderBy: { title: "asc" },
    }),
    prisma.company.findMany({
      where: { status: { not: "ARCHIVED" } },
      orderBy: { name: "asc" },
    }),
  ]);

  const dayQueries = tasks
    .filter((t) => t.companyId && (t.occurrenceDate || t.dueDate))
    .map((t) => {
      const day = startOfDay(t.occurrenceDate ?? t.dueDate!);
      return {
        taskId: t.id,
        companyId: t.companyId!,
        day,
        key: dayKey(t.companyId!, day),
      };
    });

  const uniqueKeys = [...new Map(dayQueries.map((q) => [q.key, q])).values()];

  const contentsByKey = new Map<
    string,
    Array<{
      id: string;
      title: string;
      type: keyof typeof contentTypeLabels;
      status: keyof typeof contentStatusLabels;
      autoGenerated: boolean;
    }>
  >();

  if (uniqueKeys.length > 0) {
    const orFilters = uniqueKeys.map((q) => ({
      companyId: q.companyId,
      publishAt: {
        gte: q.day,
        lt: addDays(q.day, 1),
      },
    }));

    const contents = await prisma.content.findMany({
      where: { OR: orFilters },
      select: {
        id: true,
        title: true,
        type: true,
        status: true,
        autoGenerated: true,
        companyId: true,
        publishAt: true,
      },
      orderBy: [{ type: "asc" }, { publishAt: "asc" }],
    });

    for (const c of contents) {
      if (!c.publishAt) continue;
      const key = dayKey(c.companyId, c.publishAt);
      const list = contentsByKey.get(key) ?? [];
      list.push({
        id: c.id,
        title: c.title,
        type: c.type,
        status: c.status,
        autoGenerated: c.autoGenerated,
      });
      contentsByKey.set(key, list);
    }
  }

  return (
    <div className="space-y-8">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="bf-page-title">İşler</h1>
          <p className="mt-1 text-sm text-black/55">
            Görev, yineleme ve içerik hedefleri tek yerde.
          </p>
        </div>
        <Link href="/work/new" className="bf-btn bf-btn-dark">
          Yeni ekle
        </Link>
      </div>

      <Card className="bf-panel">
        <form method="get" className="grid gap-3 md:grid-cols-3">
          <FormField label="Durum" htmlFor="filter-status">
            <SelectInput
              id="filter-status"
              name="status"
              defaultValue={status ?? ""}
            >
              <option value="">Tümü</option>
              {Object.entries(taskStatusLabels).map(([value, label]) => (
                <option key={value} value={value}>
                  {label}
                </option>
              ))}
            </SelectInput>
          </FormField>
          <FormField label="Firma" htmlFor="filter-company">
            <SelectInput
              id="filter-company"
              name="company"
              defaultValue={sp.company ?? ""}
            >
              <option value="">Tümü</option>
              {companies.map((c) => (
                <option key={c.id} value={c.id}>
                  {c.name}
                </option>
              ))}
            </SelectInput>
          </FormField>
          <div className="flex items-end">
            <Button type="submit" fullWidth>
              Filtrele
            </Button>
          </div>
        </form>
      </Card>

      {tasks.length === 0 && templates.length === 0 ? (
        <Card className="bf-panel">
          <p className="text-sm text-black/50">İş bulunamadı.</p>
          <Link href="/work/new" className="bf-link mt-2 inline-block text-sm">
            Yeni iş veya içerik ekle
          </Link>
        </Card>
      ) : (
        <WorkBulkList
          totalCount={tasks.length + templates.length}
          taskIds={[...templates.map((t) => t.id), ...tasks.map((t) => t.id)]}
          allowDelete={admin}
        >
          {templates.length > 0 ? (
            <div className="bf-panel !py-3">
              <p className="mb-2 text-xs font-bold uppercase tracking-[0.08em] text-black/40">
                Tekrarlayan şablonlar
              </p>
              <p className="mb-3 text-xs text-black/50">
                Bunları silmezsen takvimde içerik yeniden üretilir.
              </p>
              <div className="space-y-2">
                {templates.map((task) => {
                  const hasPlan =
                    task.planPosts +
                      task.planStories +
                      task.planReels +
                      task.planVideos >
                    0;
                  return (
                    <WorkBulkItem key={task.id} id={task.id}>
                      <div className="rounded-[8px] border border-black/8 bg-white px-3 py-3">
                        <div className="flex flex-wrap items-center justify-between gap-2">
                          <div>
                            <Link
                              href={`/tasks/${task.id}`}
                              className="font-medium hover:text-[var(--bf-accent-deep)]"
                            >
                              {task.title}
                            </Link>
                            <p className="text-xs text-black/50">
                              {taskRecurrenceLabels[task.recurrence]} ·{" "}
                              {task.company?.name ?? "Firma yok"} ·{" "}
                              {task.assignee?.name ?? "Atanmamış"}
                            </p>
                          </div>
                          <Chip size="sm">
                            {taskRecurrenceLabels[task.recurrence]}
                          </Chip>
                        </div>
                        {hasPlan ? (
                          <div className="mt-3">
                            <ContentPlanSummary
                              subtitle={`${planPeriodLabels[task.planPeriod]} hedefler`}
                              items={planItemsFromTask(task)}
                            />
                          </div>
                        ) : null}
                      </div>
                    </WorkBulkItem>
                  );
                })}
              </div>
            </div>
          ) : null}

          {tasks.map((task) => {
            const day = task.occurrenceDate ?? task.dueDate;
            const related =
              task.companyId && day
                ? (contentsByKey.get(dayKey(task.companyId, day)) ?? [])
                : [];
            const hasPlan =
              task.planPosts +
                task.planStories +
                task.planReels +
                task.planVideos >
              0;

            return (
              <WorkBulkItem key={task.id} id={task.id}>
                <Card className="bf-panel">
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div className="min-w-0">
                      <div className="flex flex-wrap items-center gap-2">
                        <Link
                          href={`/tasks/${task.id}`}
                          className="font-semibold hover:text-[var(--bf-accent-deep)]"
                        >
                          {task.title}
                        </Link>
                        {task.recurrenceOfId ? (
                          <Chip size="sm">Tekrar</Chip>
                        ) : null}
                        <Chip size="sm">{taskStatusLabels[task.status]}</Chip>
                        <Chip size="sm">
                          {taskPriorityLabels[task.priority]}
                        </Chip>
                      </div>
                      <p className="mt-1 text-sm text-black/55">
                        {task.company?.name ?? "Firma yok"} ·{" "}
                        {task.assignee?.name ?? "Atanmamış"}
                        {task.dueDate
                          ? ` · ${format(task.dueDate, "d MMM yyyy HH:mm", {
                              locale: tr,
                            })}`
                          : ""}
                      </p>
                    </div>
                    <div className="flex flex-wrap items-center gap-2">
                      <Link
                        href={`/tasks/${task.id}#duzenle`}
                        className="bf-link text-sm"
                      >
                        Düzenle
                      </Link>
                      {task.companyId ? (
                        <Link
                          href={`/work/new?type=content&company=${task.companyId}`}
                          className="bf-link text-sm"
                        >
                          İçerik ekle
                        </Link>
                      ) : null}
                    </div>
                  </div>

                  {hasPlan ? (
                    <div className="mt-4">
                      <ContentPlanSummary
                        subtitle={`${planPeriodLabels[task.planPeriod]} hedefler`}
                        items={planItemsFromTask(task)}
                      />
                    </div>
                  ) : null}

                  {related.length > 0 ? (
                    <div className="mt-4 border-t border-black/6 pt-3">
                      <p className="mb-2 text-xs font-bold uppercase tracking-[0.08em] text-black/40">
                        Günlük içerikler
                        {day
                          ? ` · ${format(day, "d MMM", { locale: tr })}`
                          : ""}
                      </p>
                      <ul className="space-y-1.5">
                        {related.map((c) => (
                          <li
                            key={c.id}
                            className="flex flex-wrap items-center gap-2 text-sm"
                          >
                            <Chip size="sm">{contentTypeLabels[c.type]}</Chip>
                            <Link
                              href={`/contents/${c.id}`}
                              className="bf-link font-medium"
                            >
                              {c.title}
                            </Link>
                            <Chip size="sm">
                              {contentStatusLabels[c.status]}
                            </Chip>
                            {c.autoGenerated ? (
                              <span className="text-xs text-black/40">
                                Otomatik
                              </span>
                            ) : null}
                          </li>
                        ))}
                      </ul>
                    </div>
                  ) : task.companyId && day ? (
                    <p className="mt-3 text-xs text-black/40">
                      Bu gün için henüz içerik slotu yok.
                    </p>
                  ) : null}
                </Card>
              </WorkBulkItem>
            );
          })}
        </WorkBulkList>
      )}
    </div>
  );
}
