import Link from "next/link";
import { endOfDay, format, startOfDay } from "date-fns";
import { tr } from "date-fns/locale";
import { syncRecurringTasks, toggleTaskDone } from "@/actions/tasks";
import { DailyContentChecklist } from "@/components/contents/daily-content-checklist";
import { Role, TaskStatus } from "@/generated/prisma/client";
import { prisma } from "@/lib/db";
import { syncDueDateNotifications } from "@/lib/notifications";
import { excludeTaskTemplatesFilter } from "@/lib/recurring-tasks";
import { requireSession } from "@/lib/session";

export default async function TodayPage() {
  const session = await requireSession();
  const userId = session.user.id;
  const admin = session.user.role === Role.ADMIN;

  await Promise.all([
    syncDueDateNotifications(userId),
    syncRecurringTasks(7),
  ]);

  const now = new Date();
  const todayStart = startOfDay(now);
  const todayEnd = endOfDay(now);
  const dateLabel = format(now, "d MMMM yyyy, EEEE", { locale: tr });

  const taskScope = excludeTaskTemplatesFilter();

  const todayContentWhere = {
    OR: [
      { publishAt: { gte: todayStart, lte: todayEnd } },
      {
        publishAt: null,
        createdAt: { gte: todayStart, lte: todayEnd },
      },
    ],
  };

  const [todayTasks, overdueTasks, todayChecklist] = await Promise.all([
    prisma.task.findMany({
      where: {
        ...taskScope,
        status: { not: TaskStatus.DONE },
        dueDate: { gte: todayStart, lte: todayEnd },
      },
      include: { company: true, assignee: true },
      orderBy: { dueDate: "asc" },
      take: 20,
    }),
    prisma.task.findMany({
      where: {
        ...taskScope,
        status: { not: TaskStatus.DONE },
        dueDate: { lt: todayStart },
      },
      include: { company: true, assignee: true },
      orderBy: { dueDate: "asc" },
      take: 10,
    }),
    prisma.content.findMany({
      where: todayContentWhere,
      include: {
        company: { select: { id: true, name: true } },
        author: { select: { id: true, name: true } },
      },
      orderBy: [{ publishAt: "asc" }, { createdAt: "asc" }],
    }),
  ]);

  function canMarkTask(task: {
    assigneeId: string | null;
    creatorId: string;
  }) {
    return (
      admin ||
      task.assigneeId === userId ||
      (!task.assigneeId && task.creatorId === userId)
    );
  }

  const checklistItems = todayChecklist.map((c) => ({
    id: c.id,
    title: c.title,
    type: c.type,
    platform: c.platform,
    status: c.status,
    companyId: c.companyId,
    companyName: c.company.name,
    personName: c.author.name,
    timeLabel: format(c.publishAt ?? c.createdAt, "HH:mm", { locale: tr }),
    autoGenerated: c.autoGenerated,
    canToggle: admin || c.authorId === userId,
  }));

  const doneToday = checklistItems.filter((c) => c.status === "PUBLISHED").length;
  const leftToday = checklistItems.length - doneToday;

  return (
    <div className="bf-page mx-auto max-w-3xl space-y-8">
      <header>
        <h1 className="bf-page-title">Dashboard</h1>
        <p className="bf-page-sub capitalize">{dateLabel}</p>
        <p className="mt-2 text-sm text-[var(--bf-muted)]">
          Merhaba {session.user.name}. Herkesin işini görürsün
          {admin
            ? "; admin olarak hepsine dokunabilirsin."
            : "; yalnızca sana atananlara dokunabilirsin."}
        </p>
      </header>

      <section className="grid grid-cols-2 gap-3 sm:grid-cols-3">
        <div className="bf-stat rounded-[10px] border border-[var(--da-line)] bg-white/80 px-4 py-3">
          <p className="text-xs font-bold uppercase tracking-[0.06em] text-[var(--bf-muted)]">
            Kalan paylaşım
          </p>
          <p className="bf-brand mt-2 text-3xl text-[var(--bf-ink)]">
            {leftToday}
            <span className="text-lg text-[var(--bf-muted)]">
              /{checklistItems.length}
            </span>
          </p>
        </div>
        <div className="bf-stat rounded-[10px] border border-[var(--da-line)] bg-white/80 px-4 py-3">
          <p className="text-xs font-bold uppercase tracking-[0.06em] text-[var(--bf-muted)]">
            Bugünkü görev
          </p>
          <p className="bf-brand mt-2 text-3xl text-[var(--bf-ink)]">
            {todayTasks.length}
          </p>
        </div>
        <div className="bf-stat col-span-2 rounded-[10px] border border-[var(--da-line)] bg-white/80 px-4 py-3 sm:col-span-1">
          <p className="text-xs font-bold uppercase tracking-[0.06em] text-[var(--bf-muted)]">
            Gecikmiş
          </p>
          <p
            className={`bf-brand mt-2 text-3xl ${
              overdueTasks.length > 0
                ? "text-[var(--da-purple)]"
                : "text-[var(--bf-ink)]"
            }`}
          >
            {overdueTasks.length}
          </p>
        </div>
      </section>

      {overdueTasks.length > 0 ? (
        <section className="bf-panel border-[var(--da-purple)]/30">
          <h2 className="bf-panel-title">Gecikmiş işler</h2>
          <p className="mt-1 text-sm text-[var(--bf-muted)]">
            Önce bunları bitir
          </p>
          <ul className="mt-3 space-y-0">
            {overdueTasks.map((task) => (
              <li key={task.id} className="bf-list-row items-center">
                <div className="min-w-0">
                  <Link
                    href={`/tasks/${task.id}`}
                    className="bf-link font-semibold"
                  >
                    {task.title}
                  </Link>
                  <p className="mt-0.5 text-xs text-[var(--bf-muted)]">
                    {task.company?.name ?? "Firma yok"}
                    {task.assignee
                      ? ` · ${task.assignee.name}`
                      : " · Atanmamış"}
                    {task.dueDate
                      ? ` · ${format(task.dueDate, "d MMM", { locale: tr })}`
                      : ""}
                  </p>
                </div>
                {canMarkTask(task) ? (
                  <form action={toggleTaskDone.bind(null, task.id)}>
                    <button
                      type="submit"
                      className="bf-btn bf-btn-dark text-sm"
                    >
                      Tamamla
                    </button>
                  </form>
                ) : null}
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      <section className="bf-panel">
        <h2 className="bf-panel-title">Bugünkü paylaşımlar</h2>
        <p className="mt-1 text-sm text-[var(--bf-muted)]">
          Post / story / reel / video — yalnızca sana atananlarda tik görünür
        </p>
        <div className="mt-4">
          <DailyContentChecklist items={checklistItems} />
        </div>
      </section>

      <section className="bf-panel">
        <div className="mb-3 flex items-end justify-between gap-3">
          <div>
            <h2 className="bf-panel-title">Bugünkü görevler</h2>
            <p className="mt-1 text-sm text-[var(--bf-muted)]">
              Deadline’ı bugün olanlar
            </p>
          </div>
          {admin ? (
            <Link href="/work" className="bf-link text-sm font-semibold">
              Tümü
            </Link>
          ) : null}
        </div>
        {todayTasks.length === 0 ? (
          <p className="text-sm text-[var(--bf-muted)]">
            Bugün için açık görev yok.
          </p>
        ) : (
          <ul className="space-y-0">
            {todayTasks.map((task) => (
              <li key={task.id} className="bf-list-row items-center">
                <div className="min-w-0">
                  <Link
                    href={`/tasks/${task.id}`}
                    className="bf-link font-semibold"
                  >
                    {task.title}
                  </Link>
                  <p className="mt-0.5 text-xs text-[var(--bf-muted)]">
                    {task.company?.name ?? "Firma yok"}
                    {task.assignee
                      ? ` · ${task.assignee.name}`
                      : " · Atanmamış"}
                    {task.dueDate
                      ? ` · Son ${format(task.dueDate, "HH:mm")}`
                      : ""}
                  </p>
                </div>
                {canMarkTask(task) ? (
                  <form action={toggleTaskDone.bind(null, task.id)}>
                    <button type="submit" className="bf-btn text-sm">
                      Tamamla
                    </button>
                  </form>
                ) : null}
              </li>
            ))}
          </ul>
        )}
      </section>

      <p className="text-center text-sm text-[var(--bf-muted)]">
        Haftalık görünüm için{" "}
        <Link href="/calendar" className="bf-link font-semibold">
          Takvim
        </Link>
        ’e bak.
      </p>
    </div>
  );
}
