"use client";

import Link from "next/link";
import { useMemo, useOptimistic, useTransition } from "react";
import { toggleContentDone } from "@/actions/contents";
import {
  contentTypeLabels,
  platformLabels,
} from "@/lib/labels";
import type {
  ContentStatus,
  ContentType,
  SocialPlatform,
} from "@/generated/prisma/enums";

export type DailyChecklistItem = {
  id: string;
  title: string;
  type: ContentType;
  platform: SocialPlatform;
  status: ContentStatus;
  companyId: string;
  companyName: string;
  personName?: string;
  timeLabel: string;
  autoGenerated?: boolean;
  /** Sadece atanan tik atabilir — takvimle aynı */
  canToggle?: boolean;
};

const TYPE_ORDER: ContentType[] = ["POST", "STORY", "REEL", "VIDEO"];

function isDone(status: ContentStatus) {
  return status === "PUBLISHED";
}

export function DailyContentChecklist({
  items: initialItems,
}: {
  items: DailyChecklistItem[];
}) {
  const [pending, startTransition] = useTransition();
  const [items, setOptimistic] = useOptimistic(
    initialItems,
    (current, update: { id: string; done: boolean }) =>
      current.map((item) =>
        item.id === update.id
          ? {
              ...item,
              status: update.done
                ? ("PUBLISHED" as const)
                : ("SCHEDULED" as const),
            }
          : item,
      ),
  );

  const groups = useMemo(() => {
    const byCompany = new Map<
      string,
      { companyId: string; companyName: string; byType: Map<ContentType, DailyChecklistItem[]> }
    >();

    for (const item of items) {
      let company = byCompany.get(item.companyId);
      if (!company) {
        company = {
          companyId: item.companyId,
          companyName: item.companyName,
          byType: new Map(),
        };
        byCompany.set(item.companyId, company);
      }
      const list = company.byType.get(item.type) ?? [];
      list.push(item);
      company.byType.set(item.type, list);
    }

    return [...byCompany.values()].sort((a, b) =>
      a.companyName.localeCompare(b.companyName, "tr"),
    );
  }, [items]);

  const doneCount = items.filter((i) => isDone(i.status)).length;

  function onToggle(item: DailyChecklistItem) {
    if (!item.canToggle) return;
    const nextDone = !isDone(item.status);
    startTransition(async () => {
      setOptimistic({ id: item.id, done: nextDone });
      try {
        await toggleContentDone(item.id);
      } catch {
        setOptimistic({ id: item.id, done: !nextDone });
      }
    });
  }

  if (items.length === 0) {
    return (
      <p className="text-sm text-[var(--da-muted)]">
        Bugün için paylaşım yok. Rahat bir gün — veya Takvim’den kontrol et.
      </p>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between gap-3">
        <p className="text-sm text-[var(--da-muted)]">
          Post / story / reel / video ayrı ayrı tiklenir — {doneCount}/
          {items.length} tamamlandı
        </p>
        {pending ? (
          <span className="text-xs text-[var(--da-muted)]">Kaydediliyor…</span>
        ) : null}
      </div>

      {groups.map((company) => (
        <div key={company.companyId} className="space-y-4">
          <h3 className="text-sm font-bold text-[var(--da-ink)]">
            {company.companyName}
          </h3>

          <div className="grid gap-4 md:grid-cols-2">
            {TYPE_ORDER.map((type) => {
              const typeItems = company.byType.get(type);
              if (!typeItems || typeItems.length === 0) return null;
              const typeDone = typeItems.filter((i) => isDone(i.status)).length;
              const allDone = typeDone === typeItems.length;

              return (
                <div
                  key={type}
                  className="rounded-[10px] border border-[var(--da-line)] bg-white/70 p-3"
                >
                  <div className="mb-2 flex items-baseline justify-between gap-2">
                    <p className="text-xs font-bold uppercase tracking-[0.06em] text-[var(--da-muted)]">
                      {contentTypeLabels[type]}
                    </p>
                    <p
                      className={`text-sm font-semibold ${
                        allDone
                          ? "text-[var(--da-purple)]"
                          : "text-[var(--da-ink)]"
                      }`}
                    >
                      {typeDone}/{typeItems.length}
                    </p>
                  </div>

                  <ul className="space-y-1">
                    {typeItems.map((item, index) => {
                      const done = isDone(item.status);
                      const canToggle = !!item.canToggle;
                      return (
                        <li key={item.id}>
                          <div
                            className={`flex items-start gap-2 rounded-lg px-1 py-1.5 ${
                              canToggle ? "hover:bg-black/[0.03]" : ""
                            }`}
                          >
                            {canToggle ? (
                              <input
                                type="checkbox"
                                className="bf-check mt-0.5 cursor-pointer"
                                checked={done}
                                onChange={() => onToggle(item)}
                                aria-label={`${contentTypeLabels[type]} ${index + 1} tamamlandı`}
                              />
                            ) : (
                              <span
                                className={`mt-0.5 inline-flex h-4 w-4 shrink-0 items-center justify-center rounded border text-[10px] ${
                                  done
                                    ? "border-[var(--da-purple)] bg-[var(--da-purple)]/15 text-[var(--da-purple)]"
                                    : "border-[var(--da-line)] text-[var(--da-muted)]"
                                }`}
                                title="Yalnızca atanan kişi işaretleyebilir"
                                aria-hidden
                              >
                                {done ? "✓" : ""}
                              </span>
                            )}
                            <span className="min-w-0 flex-1">
                              <span
                                className={`block text-sm font-medium ${
                                  done
                                    ? "text-[var(--da-muted)] line-through"
                                    : "text-[var(--da-ink)]"
                                }`}
                              >
                                {contentTypeLabels[type]} {index + 1}
                                <span className="ml-1.5 font-normal text-[var(--da-muted)]">
                                  · {platformLabels[item.platform]} ·{" "}
                                  {item.timeLabel}
                                  {item.personName
                                    ? ` · ${item.personName}`
                                    : ""}
                                </span>
                              </span>
                              <Link
                                href={`/contents/${item.id}`}
                                className="bf-link mt-0.5 block truncate text-xs"
                              >
                                {item.title}
                              </Link>
                            </span>
                          </div>
                        </li>
                      );
                    })}
                  </ul>
                </div>
              );
            })}
          </div>
        </div>
      ))}
    </div>
  );
}
