import Link from "next/link";
import { notFound } from "next/navigation";
import { Button, Card, Chip } from "@heroui/react";
import { format } from "date-fns";
import { tr } from "date-fns/locale";
import {
  approveContent,
  deleteContent,
  markPublished,
  requestRevision,
  scheduleContent,
  submitForReview,
  toggleContentDone,
  updateContent,
} from "@/actions/contents";
import {
  FormField,
  SelectInput,
  TextAreaInput,
  TextInput,
} from "@/components/ui/form-field";
import { ContentStatus, Role } from "@/generated/prisma/client";
import { prisma } from "@/lib/db";
import {
  contentStatusLabels,
  contentTypeLabels,
  platformLabels,
} from "@/lib/labels";
import { requireSession } from "@/lib/session";

export default async function ContentDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const session = await requireSession();
  const admin = session.user.role === Role.ADMIN;

  const [content, companies] = await Promise.all([
    prisma.content.findUnique({
      where: { id },
      include: {
        company: true,
        author: true,
        revisions: {
          include: { requestedBy: true },
          orderBy: { createdAt: "desc" },
        },
      },
    }),
    prisma.company.findMany({
      where: { status: { not: "ARCHIVED" } },
      orderBy: { name: "asc" },
    }),
  ]);

  if (!content) notFound();

  const canEdit =
    admin || content.authorId === session.user.id;
  const canMarkDone = admin || content.authorId === session.user.id;
  const publishLocal = content.publishAt
    ? format(content.publishAt, "yyyy-MM-dd'T'HH:mm")
    : "";

  return (
    <div className="space-y-8">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <Link
            href={admin ? "/work" : "/"}
            className="text-sm text-black/50 hover:text-[var(--bf-accent-deep)]"
          >
            {admin ? "← İşler" : "← Dashboard"}
          </Link>
          <h1 className="mt-2 bf-page-title">
            {content.title}
          </h1>
          <div className="mt-2 flex flex-wrap gap-2">
            {content.autoGenerated ? <Chip size="sm">Otomatik</Chip> : null}
            <Chip size="sm">{contentStatusLabels[content.status]}</Chip>
            <Chip size="sm">{platformLabels[content.platform]}</Chip>
            <Chip size="sm">{contentTypeLabels[content.type]}</Chip>
          </div>
          <p className="mt-2 text-sm text-black/55">
            {content.company.name} · {content.author.name}
            {content.publishAt
              ? ` · ${format(content.publishAt, "d MMM yyyy HH:mm", { locale: tr })}`
              : ""}
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          {canEdit ? (
            <Link href="#duzenle" className="bf-btn">
              Düzenle
            </Link>
          ) : null}
          {admin ? (
            <form action={deleteContent.bind(null, content.id)}>
              <Button type="submit" variant="danger" size="sm">
                Sil
              </Button>
            </form>
          ) : null}
        </div>
      </div>

      <Card className="bf-panel">
        <Card.Header className="mb-3">
          <Card.Title>İçerik</Card.Title>
        </Card.Header>
        <Card.Content className="space-y-3 whitespace-pre-wrap text-sm leading-relaxed">
          <p>{content.body}</p>
          {content.notes ? (
            <p className="text-black/55">Not: {content.notes}</p>
          ) : null}
        </Card.Content>
      </Card>

      <Card className="bf-panel">
        <Card.Header className="mb-4">
          <Card.Title>Durum aksiyonları</Card.Title>
        </Card.Header>
        <Card.Content className="flex flex-wrap gap-3">
          {(content.status === ContentStatus.DRAFT ||
            content.status === ContentStatus.PREPARING) &&
          canEdit ? (
            <form action={submitForReview.bind(null, content.id)}>
              <Button type="submit">Kontrole gönder</Button>
            </form>
          ) : null}

          {admin && content.status === ContentStatus.TEAM_REVIEW ? (
            <>
              <form action={approveContent.bind(null, content.id)}>
                <Button type="submit">Onayla</Button>
              </form>
              <form
                action={requestRevision.bind(null, content.id)}
                className="flex flex-wrap items-end gap-2"
              >
                <FormField label="Revizyon notu" htmlFor="comment">
                  <TextInput id="comment" name="comment" required />
                </FormField>
                <Button type="submit" variant="secondary">
                  Revizyon iste
                </Button>
              </form>
            </>
          ) : null}

          {admin &&
          (content.status === ContentStatus.APPROVED ||
            content.status === ContentStatus.SCHEDULED) ? (
            <>
              <form
                action={scheduleContent.bind(null, content.id)}
                className="flex flex-wrap items-end gap-2"
              >
                <FormField label="Planlama zamanı" htmlFor="publishAt">
                  <TextInput
                    id="publishAt"
                    name="publishAt"
                    type="datetime-local"
                    required
                    defaultValue={publishLocal}
                  />
                </FormField>
                <Button type="submit" variant="secondary">
                  Planla
                </Button>
              </form>
              <form action={markPublished.bind(null, content.id)}>
                <Button type="submit">Yayınlandı işaretle</Button>
              </form>
            </>
          ) : null}

          {canMarkDone && content.status !== ContentStatus.PUBLISHED ? (
            <form action={toggleContentDone.bind(null, content.id)}>
              <Button type="submit">Tamamlandı ✓</Button>
            </form>
          ) : null}

          {canMarkDone && content.status === ContentStatus.PUBLISHED ? (
            <form action={toggleContentDone.bind(null, content.id)}>
              <Button type="submit" variant="secondary">
                Tamamlandı işaretini kaldır
              </Button>
            </form>
          ) : null}
        </Card.Content>
      </Card>

      {canEdit ? (
        <Card id="duzenle" className="bf-panel">
          <Card.Header className="mb-4">
            <Card.Title>İçeriği düzenle</Card.Title>
          </Card.Header>
          <Card.Content>
            <form
              action={updateContent.bind(null, content.id)}
              className="grid gap-4 md:grid-cols-2"
            >
              <div className="md:col-span-2">
                <FormField label="Başlık" htmlFor="title">
                  <TextInput
                    id="title"
                    name="title"
                    required
                    defaultValue={content.title}
                  />
                </FormField>
              </div>
              <FormField label="Firma" htmlFor="companyId">
                <SelectInput
                  id="companyId"
                  name="companyId"
                  defaultValue={content.companyId}
                >
                  {companies.map((c) => (
                    <option key={c.id} value={c.id}>
                      {c.name}
                    </option>
                  ))}
                </SelectInput>
              </FormField>
              <FormField label="Platform" htmlFor="platform">
                <SelectInput
                  id="platform"
                  name="platform"
                  defaultValue={content.platform}
                >
                  {Object.entries(platformLabels).map(([value, label]) => (
                    <option key={value} value={value}>
                      {label}
                    </option>
                  ))}
                </SelectInput>
              </FormField>
              <FormField label="Tür" htmlFor="type">
                <SelectInput
                  id="type"
                  name="type"
                  defaultValue={content.type}
                >
                  {Object.entries(contentTypeLabels).map(([value, label]) => (
                    <option key={value} value={value}>
                      {label}
                    </option>
                  ))}
                </SelectInput>
              </FormField>
              <FormField label="Yayın zamanı" htmlFor="publishAt-edit">
                <TextInput
                  id="publishAt-edit"
                  name="publishAt"
                  type="datetime-local"
                  defaultValue={publishLocal}
                />
              </FormField>
              <div className="md:col-span-2">
                <FormField label="İçerik metni" htmlFor="body">
                  <TextAreaInput
                    id="body"
                    name="body"
                    required
                    defaultValue={content.body}
                  />
                </FormField>
              </div>
              <div className="md:col-span-2">
                <FormField label="Notlar" htmlFor="notes">
                  <TextAreaInput
                    id="notes"
                    name="notes"
                    defaultValue={content.notes ?? ""}
                  />
                </FormField>
              </div>
              <input type="hidden" name="status" value={content.status} />
              <div className="md:col-span-2">
                <Button type="submit">Kaydet</Button>
              </div>
            </form>
          </Card.Content>
        </Card>
      ) : null}

      <Card className="bf-panel">
        <Card.Header className="mb-4">
          <Card.Title>Revizyon geçmişi</Card.Title>
        </Card.Header>
        <Card.Content>
          {content.revisions.length === 0 ? (
            <p className="text-sm text-black/50">Henüz revizyon yok.</p>
          ) : (
            <ul className="space-y-4">
              {content.revisions.map((rev) => (
                <li
                  key={rev.id}
                  className="rounded-xl border border-black/8 bg-white/50 p-4"
                >
                  <div className="flex flex-wrap items-center justify-between gap-2">
                    <Chip size="sm">{rev.action}</Chip>
                    <span className="text-xs text-black/50">
                      {rev.requestedBy.name} ·{" "}
                      {format(rev.createdAt, "d MMM yyyy HH:mm", {
                        locale: tr,
                      })}
                    </span>
                  </div>
                  <p className="mt-2 text-sm whitespace-pre-wrap">
                    {rev.comment}
                  </p>
                </li>
              ))}
            </ul>
          )}
        </Card.Content>
      </Card>
    </div>
  );
}
